### ISSUE TITLE
When scrolling past the map cursor gets caught

### ISSUE THREAD

**Issue by jkrup** [MeteorCampNYC/MeteorCampNYC#1]
Desired behavior: When scrolling  on page over the map you should continue scrolling, ideally only when a scroll starts would the map zoom.

Temporary fix might be to just completely disable scrolling zoom in google maps.

**Comment by jkrup** [comment]
http://stackoverflow.com/questions/21992498/disable-mouse-scroll-wheel-zoom-on-embedded-google-maps

**Comment by purplecones** [comment]
Should get fixed with PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/5

followed : http://stackoverflow.com/questions/24768772/prevent-a-google-maps-iframe-from-capturing-the-mouses-scrolling-wheel-behavior

**Comment by purplecones** [comment]
@alanning  @alimgafar  this is fixed and should be closed
