### ISSUE TITLE
Add section for volunteers

### ISSUE THREAD

**Issue by purplecones** [MeteorCampNYC/MeteorCampNYC#10]
Still need to determine where to add this on the page

**Comment by purplecones** [comment]
@alimgafar do you have a list of everyones names, bios, titles, avatars that you want to include in this section? Maybe we just include names and avatars and split between organizing chairs and volunteers?

**Comment by alimgafar** [comment]
I'll work on this tomorrow. I like your suggestion for now.

Chairs: Alim S. Gafar, Adrian Lanning
Volunteers: Mirza Joldic, Dakoda Wogan, Alex Bachuk, Greg Schwedock, Alex Fulsome, Edgar Muentes

Is there anyone you can think of right now that I'm missing?

**Comment by alimgafar** [comment]
I'd still like to add this to the site. I think people who worked on it should get recognition and credit. Let's revisit this.
