### ISSUE TITLE
Add MDG, OK GROW! and Checkmate Creations as partners

### ISSUE THREAD

**Issue by alanning** [MeteorCampNYC/MeteorCampNYC#12]
Meteor Development Group - meteor.com

OK GROW! - https://www.okgrow.com/
We can use the logo that they have on their homepage, or I have some other logo assets that we can use if needed.

Checkmate Creations - http://www.checkmatecreations.com/
Use logo from their website.

**Comment by purplecones** [comment]
@alanning PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/13 addresses this
