### ISSUE TITLE
Speaker notes have to be corrected

### ISSUE THREAD

**Issue by alimgafar** [MeteorCampNYC/MeteorCampNYC#19]
Abigail Watson's entry: change company name from "Pentasyllabic Studios" to "Symptomatic.io"
                                      change bio to "Abigail is a bioinformaticist and curator of the Clinical Meteor Track"

Matthias Czerwonka's entry: change company name from "Innodata" to "Innoscale"

Remove periods from the last sentence of all bios.

**Comment by purplecones** [comment]
@alimgafar PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/20

**Comment by purplecones** [comment]
can be closed, updated in PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/25 with the use of presenters.json
