### ISSUE TITLE
Responsive display breaks with iPhone 4 and 5

### ISSUE THREAD

**Issue by alimgafar** [MeteorCampNYC/MeteorCampNYC#2]
When you resize the website, the page fails to degrade properly. The countdown timer now wraps to a new line and the UI is clearly not correct. There's some overhang to the right for the section-tagged areas, and the Volunteer section which is aside-tagged is wider than the others. 

Trivially replacing the <aside> with <section> didn't fix the issue in testing. This needs a bit more investigation to better understand the problem and a fix should be found.

**Comment by purplecones** [comment]
@alanning @alimgafar fixed with PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/8 please close
