### ISSUE TITLE
Staying in NYC for Meteor Camp NYC 2016

### ISSUE THREAD

**Issue by alimgafar** [MeteorCampNYC/MeteorCampNYC#22]
We need a new section to include this information. The issue title will suffice for the section heading. Here's the content:

Accommodations

Accommodations are numerous in NYC, with prices varying greatly. Discounts are available at many nearby options.

We've worked to coordinate the discounted rates at nearby lodging that are outlined below.

When booking please mention "Open Camps" as the discount code or conference, and try too book soon a rates/discounts are likely only available until Jun 16.

[The New York Marriott East Side](http://www.marriott.com/hotels/travel/nycea-new-york-marriott-east-side/) (+1.212.755.4000) has offered a rate of $199 for double rooms , which can be booked with the code "Open Camps" or preferrably booked online at with [this custom Marriott page](http://www.marriott.com/meeting-event-hotels/group-corporate-travel/groupCorp.mi?resLinkData=Open%20Camps%20Inc%20Room%20Block%5ENYCEA%60opcopcd%60199%60USD%60false%603%607/7/16%607/17/16%606/16/16&app=resvlink&stop_mobi=yes) 
[The Pod 39 & 51 hotels](http://www.thepodhotel.com/pod-discount-hotel-locations/) (+1.212.865.5700) has offered the following rates:
- Double Pod rooms at $145/night
- Queen Pod rooms at $155/night (one queen size bed, accommodates up to two people)
- Mini Bunk Bed Pod rooms at at $135 (two twin size level beds, accommodates two people)
- Bunk Bed Pod rooms at $155 (two twin size level beds, accommodates two people)

[The Hampton Inn Manhattan/United Nations](http://opencamps.org/Hampton%20Inn%20Manhattan/United%20Nations)
[The Vanderbilt YMCA](http://www.ymcanyc.org/association/guest-rooms/vanderbiltrooms) (+1212.912.2506) has offered the following rates:
- $96/night for bunk room for 2
- $85/night for single room

[Hampton Inn Manhattan/United Nations](http://hamptoninn3.hilton.com/en/hotels/new-york/hampton-inn-manhattan-united-nations-NYCUNHX/index.html) is also a good nearby option. We are still seeking a discounted rate form them and will update if/once that's available.

[Hilton Manhattan East](http://www.hiltonmanhattan.com/) is also nearby and often has good rates. We're still seeking a discounted rate form them and will update if/once that's available.

The [ONE UN New York](https://www.millenniumhotels.com/en/new-york/one-un-new-york/) is the closest hotel to the venue and located directly accross from the UN. We were unable to secure a discounted rate that ONE UN New York hotel where rates are currently start at $212/night.

Excellent affordable options are also often available on Airbnb and Booking.com.

**Comment by alimgafar** [comment]
Added to section atcamp . Still needs to be styled.

**Comment by purplecones** [comment]
added in PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/27

**Comment by purplecones** [comment]
@alimgafar please close if resolved.

**Comment by alimgafar** [comment]
Could you add links to Airbnb and Booking.com? I'll close this then.

**Comment by alimgafar** [comment]
Closing without last requested change. Stale.
