### ISSUE TITLE
The Location

### ISSUE THREAD

**Issue by alimgafar** [MeteorCampNYC/MeteorCampNYC#23]
Make the issue title the section title. Copy below:

Meteor Camp is being held this year in midtown Manhattan in New York City on the extraterritorial world headquarters of the United Nations at 405 East 42nd Street. We’re an independent camp running as part of the larger two-week [Open Camps](http://opencamps.org) (July 8 — 17) offering. Check them out if you’re interested in learning more.

New York City is served by three major international airports (Newark, JFK, and LaGuardia airports), public rail and roadway transit systems, and private car services. If you need more information about getting around, please let us know and we’ll endeavor to help out.

**Comment by alimgafar** [comment]
Added to section atcamp . Still needs to be styled.

**Comment by purplecones** [comment]
I just submitted PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/27 for this but not sure if it would cause issue now since your changes came after i submitted :-/

**Comment by purplecones** [comment]
added in PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/27

**Comment by purplecones** [comment]
@alimgafar please close if resolved.
