### ISSUE TITLE
Staying Nourished at Meteor Camp NYC

### ISSUE THREAD

**Issue by alimgafar** [MeteorCampNYC/MeteorCampNYC#24]
Again, use the issue title as the section title. Copy below:

Food and light snacks will be served to all on-site attendees at Meteor Camp NYC. This will generally include fruit and pastries in the morning and during session breaks, and a light lunch or dinner of sandwiches or salad along with snacks (fruit, cookies, chips, etc.). Beverages are available at all times, including water and coffee/tea, as well as juice and sodas during lunch/dinner/breaks. If we have contribution sprints, food will also be available for participants of these activities.

**Comment by purplecones** [comment]
added in PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/27

**Comment by purplecones** [comment]
@alimgafar please close if resolved.
