### ISSUE TITLE
The following presenters need to be added.

### ISSUE THREAD

**Issue by alimgafar** [MeteorCampNYC/MeteorCampNYC#3]
Josh Owens (talk, panelist)
Loren Sands-Ramshaw (tutorial)
Chaz Mee (panelist)
Mike Solati (talk)
Faraz Fazli (talk)
Ben Newman (??)
Slava Kim (??)
Sashko Stubailo (??)
Matthias Czerwonka (talk)
Robert Dickert (talk, panel, tutorial ??)

**Comment by alimgafar** [comment]
These remain
Faraz Fazli (talk) -- based on his June performance 
Ben Newman (??) -- suggested by Loren Sands-Ramshaw; perhaps I should initiate
Slava Kim (??) -- Adrian to hear back
Sashko Stubailo (??) -- need to reach out to him
Robert Dickert (talk, panel, tutorial ??)  -- Adrian to hear back
Matthias Czerwonka (talk) -- discussion in progress

**Comment by alimgafar** [comment]
We need the following:

Abhi Aiyer
Workpop
Abhi Aiyer is a software developer at Workpop who specializes in JavaScript and Meteor
https://twitter.com/abhiaiyer
https://github.com/abhiaiyer91
https://www.linkedin.com/in/abhi-aiyer-aa41bb42
https://medium.com/@abhiaiyer (add another link and use class="icon-pencil")

Tom Nassr
Kricket.co
Tom Nassr is a serial entreprenuer and founder of Kricket.co and Checkmate Creations
https://twitter.com/tomnassr
mailto:tomnassr@gmail.com
https://www.linkedin.com/in/tomnassr

(keep these below in comments; we're still working with MDG regarding availability)
Ben Newman
MDG or Meteor Development Group <-- see which fits better
Ben Newman is a software engineer at the Meteor Development Group
https://twitter.com/benjamn
https://github.com/benjamn
https://www.linkedin.com/in/ben-newman-09241b2

Matt DeBergalis
MDG or Meteor Development Group <-- see which fits better
Matt DeBergalis is the founder of Meteor Development Group and Act Blue
https://twitter.com/debergalis
mailto:matt@meteor.com
https://github.com/debergalis
https://www.linkedin.com/in/debergalis
http://info.meteor.com/blog/author/matt-debergalis

**Comment by purplecones** [comment]
@alimgafar Are we good with presenters now? I think they are all correctly identified in the presenters.json

**Comment by purplecones** [comment]
@alimgafar can we close this issue?

**Comment by alimgafar** [comment]
Yes. I'll re-open if we need to.
