### ISSUE TITLE
Add missing presenters

### ISSUE THREAD

**Issue by alimgafar** [MeteorCampNYC/MeteorCampNYC#39]
Peter Lee
Edgar Muentes
Rob Bisson

**Comment by purplecones** [comment]
@alimgafar PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/41

I left Peter Lee as unconfirmed until we get a pic and social profiles.

**Comment by alimgafar** [comment]
Lee did not confirm; the rest is fine.
