### ISSUE TITLE
Speaker social media links incomplete

### ISSUE THREAD

**Issue by alanning** [MeteorCampNYC/MeteorCampNYC#4]
A few of the speakers have missing social media links.  

http://meteorcamp.nyc/#bios

The icons for Twitter, Github, etc are there but clicking them takes you back to the top of the page. 

Example, Josh Owen's social media links

**Comment by purplecones** [comment]
should be fixed with PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/5/commits/29d2a6fecc2ece471022ad4fc9d2273b29c58864
