### ISSUE TITLE
Please add a section called "Attending Meteor Camp NYC 2016 the United Nations"

### ISSUE THREAD

**Issue by alimgafar** [MeteorCampNYC/MeteorCampNYC#43]
Add to the "Lodging, Food, and Nearby Activities" section under the "The Location" subsection and above the "Staying in NYC for Meteor Camp NYC 2016":

Copy from this page: http://nyccamp.org/arriving with the **Arrive Early** and **Bring ID** section modified.

Call this new subsection: "Arriving at the UN"
# Arriving at the United Nations

The United Nations Headquarters is located in the heart of New York City on 1st Avenue between 42nd and 48th Street.

Attendees can gain access to the UN site at the main entrance between East 45th and 46th streets, located at 1st Avenue, New York, NY 10017.

**Arrive Early:** Please arrive at least 45-60 minutes in advance to ensure you can make it to your desired sessions in time.

**Bring ID:** You must register in advance and a state/gov't issues photo identification is required to obtain your pass to enter the UN. While you do not need to print your ticket, we encourage you to do so. Please make sure your name on the ticket matches the name on your photo identification.

**Obtain UN Pass:** When you first arrive at the UN you must obtain a UN security pass which will allow you to enter the UN to attend NYC Camp. This badge will allow you to enter the UN throughout the day, there will be a separate pass issued for each of Training Day (Fri), Sessions Days (Sat/Sun), and Summits Day (Mon).. All attendees must have this badge visible at all times during the event.

Please review below for items allowed or prohibited by U.N Security.

Once you have picked up your name badge, you will proceed to NYC Camp?s check-in area in order to obtain your conference program and lanyard.

Finally, find your way to the appropriate room by either asking a volunteer or by following the wayfinding signs and venue map.

_The following items are **allowed:**_
- battery-operated electronic devices, as well as medical devices
- cameras, video recorders, or any type of recording device
- creams, lotions, or perfumes
- strollers
## What (not) to bring

_The following items are **strictly prohibited:** [(From the UN Security Website)](http://visit.un.org/content/security)_
- any liquid, including water
- cans and bottles
- food or beverages
- backpacks and bags larger than 14" wide x 13" high x 4" deep
- aerosol containers
- non-aerosol spray (prescriptions for medical needs are permitted)
- any pointed object other then pens and pencils (i.e., knives, knitting needles, letter openers, etc.)
- electric stun guns, martial arts weapons or devices
- guns, replica guns, ammunition, and fireworks
- knives of any size
- mace and pepper spray
- razors and box cutters

**Comment by purplecones** [comment]
@alimgafar PR https://github.com/MeteorCampNYC/MeteorCampNYC/pull/44
